// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the database
/// This must be called before any other operations
String initDatabase({required String databasePath}) =>
    RustLib.instance.api.crateApiInitDatabase(databasePath: databasePath);

/// Log a message
String logMessage({
  required String level,
  required String message,
  String? module,
}) => RustLib.instance.api.crateApiLogMessage(
  level: level,
  message: message,
  module: module,
);

/// Get logs from database
List<String> getLogs({
  String? levelFilter,
  required int limit,
  required int offset,
}) => RustLib.instance.api.crateApiGetLogs(
  levelFilter: levelFilter,
  limit: limit,
  offset: offset,
);

/// Set the current log level
String setLogLevel({required String level}) =>
    RustLib.instance.api.crateApiSetLogLevel(level: level);

/// Get the current log level
String getLogLevel() => RustLib.instance.api.crateApiGetLogLevel();

/// Test function to verify flutter_rust_bridge is working
String initApp() => RustLib.instance.api.crateApiInitApp();
