name: Deploy Specific Version

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag to deploy (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.version_tag }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.version_tag }}
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'
      
      - name: Build and Deploy
        run: |
          cargo build --release
          flutter build apk --release
          echo "Deployment of ${{ github.event.inputs.version_tag }} completed"
