name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'
      
      - name: Build Rust
        run: cargo build --release
      
      - name: Build Android APK
        run: flutter build apk --release
      
      - name: Build Linux
        run: cargo build --release --target x86_64-unknown-linux-gnu
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/libconnectias_ffi.so
            build/app/outputs/flutter-apk/app-release.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
