name: Security Audit

on:
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday at 2 AM
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    name: Security Scans
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Install security tools
        run: |
          cargo install cargo-audit
          cargo install cargo-deny
      
      - name: Rust security audit
        run: cargo audit
      
      - name: Rust license check
        run: cargo deny check
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'
      
      - name: Flutter dependency check
        run: flutter pub outdated --no-dev-dependencies
      
      - name: Flutter security analysis
        run: flutter analyze --fatal-infos
